=== oskarkraak/noplateau/experiments.dtd
<?xml encoding="UTF-8"?>

    <!ELEMENT experiment (setup,projects)>
    <!ATTLIST experiment
        xmlns CDATA #FIXED ''
        iterations CDATA #REQUIRED>

    <!ELEMENT setup (constraint,docker+,configurations,output-variables)>
    <!ATTLIST setup
        xmlns CDATA #FIXED ''>

    <!ELEMENT projects (project)+>
    <!ATTLIST projects
        xmlns CDATA #FIXED ''>

    <!ELEMENT constraint (#PCDATA)>
    <!ATTLIST constraint
        xmlns CDATA #FIXED ''>

    <!ELEMENT docker EMPTY>
    <!ATTLIST docker
        xmlns CDATA #FIXED ''
        name NMTOKEN #REQUIRED
        path CDATA #REQUIRED
        version NMTOKEN #REQUIRED>

    <!ELEMENT configurations (global,configuration+)>
    <!ATTLIST configurations
        xmlns CDATA #FIXED ''>

    <!ELEMENT output-variables (output-variable)+>
    <!ATTLIST output-variables
        xmlns CDATA #FIXED ''>

    <!ELEMENT project (name,version,repository,description,sources,modules)>
    <!ATTLIST project
        xmlns CDATA #FIXED ''>

    <!ELEMENT global (option)+>
    <!ATTLIST global
        xmlns CDATA #FIXED ''>

    <!ELEMENT configuration (option)+>
    <!ATTLIST configuration
        xmlns CDATA #FIXED ''
        id NMTOKEN #REQUIRED>

    <!ELEMENT output-variable (#PCDATA)>
    <!ATTLIST output-variable
        xmlns CDATA #FIXED ''>

    <!ELEMENT name (#PCDATA)>
    <!ATTLIST name
        xmlns CDATA #FIXED ''>

    <!ELEMENT version (#PCDATA)>
    <!ATTLIST version
        xmlns CDATA #FIXED ''>

    <!ELEMENT repository (#PCDATA)>
    <!ATTLIST repository
        xmlns CDATA #FIXED ''>

    <!ELEMENT description (#PCDATA)>
    <!ATTLIST description
        xmlns CDATA #FIXED ''>

    <!ELEMENT sources (#PCDATA)>
    <!ATTLIST sources
        xmlns CDATA #FIXED ''>

    <!ELEMENT modules (module)+>
    <!ATTLIST modules
        xmlns CDATA #FIXED ''>

    <!ELEMENT module (#PCDATA)>
    <!ATTLIST module
        xmlns CDATA #FIXED ''>

    <!ELEMENT option EMPTY>
    <!ATTLIST option
        xmlns CDATA #FIXED ''
        key NMTOKEN #REQUIRED
        value NMTOKEN #REQUIRED>

=== oskarkraak/noplateau/experiment-projects.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE experiment SYSTEM "experiments.dtd">
<experiment iterations="30">
  <setup>
    <constraint></constraint>
    <docker path="ERROR" name="pynguin" version="b178e2a9"/>
    <configurations>
      <global>
        <option key="maximum-search-time" value="10"/>
        <option key="poor" value=""/>
      </global>
      <configuration id="MOSA-TypeHints">
        <option key="algorithm" value="MOSA"/>
        <option key="type_inference_strategy" value="TYPE_HINTS"/>
      </configuration>
    </configurations>
    <output-variables>
      <output-variable>TargetModule</output-variable>
      <output-variable>ConfigurationId</output-variable>
      <output-variable>ProjectName</output-variable>
      <output-variable>TotalTime</output-variable>
      <output-variable>AlgorithmIterations</output-variable>
      <output-variable>Coverage</output-variable>
      <output-variable>RandomSeed</output-variable>
      <output-variable>CodeObjects</output-variable>
      <output-variable>Predicates</output-variable>
      <output-variable>Goals</output-variable>
      <output-variable>GeneratableTypes</output-variable>
      <output-variable>AccessibleObjectsUnderTest</output-variable>
      <output-variable>NumberOfCreatedMutants</output-variable>
      <output-variable>NumberOfKilledMutants</output-variable>
      <output-variable>NumberOfTimedOutMutants</output-variable>
      <output-variable>MutationScore</output-variable>
      <output-variable>CoverageTimeline</output-variable>
    </output-variables>
  </setup>
  <projects>
    <project>
      <name>flake8</name>
      <version>3.9.0</version>
      <repository>https://gitlab.com/pycqa/flake8</repository>
      <description>Modular source code checker</description>
      <sources>projects/flake8/src</sources>
      <modules>
        <module>flake8.main.debug</module>
        <module>flake8.options.aggregator</module>
        <module>flake8.statistics</module>
      </modules>
    </project>
    <project>
      <name>pypara</name>
      <version>0.0.24</version>
      <repository>https://github.com/vst/pypara</repository>
      <description>Currencies, Monetary Value Objects, Arithmetic, and Conversion</description>
      <sources>projects/pypara</sources>
      <modules>
        <module>pypara.accounting.journaling</module>
      </modules>
    </project>
    <project>
      <name>python-semantic-release</name>
      <version>7.15.3</version>
      <repository>https://github.com/relekang/python-semantic-release</repository>
      <description>Automated Semantic Versioning for Python</description>
      <sources>projects/python-semantic-release</sources>
      <modules>
        <module>semantic_release.ci_checks</module>
      </modules>
    </project>
    <project>
      <name>docstring_parser</name>
      <version>0.7.3</version>
      <repository>https://github.com/rr-/docstring_parser</repository>
      <description>Parser for Python docstrings</description>
      <sources>projects/docstring_parser</sources>
      <modules>
        <module>docstring_parser.google</module>
      </modules>
    </project>
    <project>
      <name>dataclasses-json</name>
      <version>0.5.2</version>
      <repository>https://github.com/lidatong/dataclasses-json</repository>
      <description>Encoding and Decoding Dataclasses to and from JSON</description>
      <sources>projects/dataclasses-json</sources>
      <modules>
        <module>dataclasses_json.core</module>
      </modules>
    </project>
    <project>
      <name>httpie</name>
      <version>2.4.0</version>
      <repository>https://github.com/httpie/httpie</repository>
      <description>Modern, user-friendly command-line HTTP client for the API area</description>
      <sources>projects/httpie</sources>
      <modules>
        <module>httpie.utils</module>
      </modules>
    </project>
    <project>
      <name>pytutils</name>
      <version>0.4.1</version>
      <repository>https://github.com/akatrevorjay/pytutils</repository>
      <description>Heap of garbage from trevorj</description>
      <sources>projects/pytutils</sources>
      <modules>
        <module>pytutils.excs</module>
        <module>pytutils.env</module>
      </modules>
    </project>
    <project>
      <name>pypara</name>
      <version>0.0.24</version>
      <repository>https://github.com/vst/pypara</repository>
      <description>Currencies, Monetary Value Objects, Arithmetic, and Conversion</description>
      <sources>projects/pypara</sources>
      <modules>
        <module>pypara.commons.others</module>
      </modules>
    </project>
    <project>
      <name>py-backwards</name>
      <version>0.7</version>
      <repository>https://github.com/nvbn/py-backwards</repository>
      <description>Bring Python 3.6 features to older versions</description>
      <sources>projects/py-backwards</sources>
      <modules>
        <module>py_backwards.conf</module>
      </modules>
    </project>
    <project>
      <name>httpie</name>
      <version>2.4.0</version>
      <repository>https://github.com/httpie/httpie</repository>
      <description>Modern, user-friendly command-line HTTP client for the API area</description>
      <sources>projects/httpie</sources>
      <modules>
        <module>httpie.output.formatters.json</module>
      </modules>
    </project>
    <project>
      <name>docstring_parser</name>
      <version>0.7.3</version>
      <repository>https://github.com/rr-/docstring_parser</repository>
      <description>Parser for Python docstrings</description>
      <sources>projects/docstring_parser</sources>
      <modules>
        <module>docstring_parser.numpydoc</module>
      </modules>
    </project>
    <project>
      <name>isort</name>
      <version>5.8.0</version>
      <repository>https://github.com/PyCQA/isort</repository>
      <description>Import sorting</description>
      <sources>projects/isort</sources>
      <modules>
        <module>isort.io</module>
      </modules>
    </project>
    <project>
      <name>flutils</name>
      <version>0.7</version>
      <repository>https://gitlab.com/finite-loop/flutils</repository>
      <description>Utilities for Python</description>
      <sources>projects/flutils</sources>
      <modules>
        <module>flutils.pathutils</module>
        <module>flutils.decorators</module>
      </modules>
    </project>
    <project>
      <name>python-semantic-release</name>
      <version>7.15.3</version>
      <repository>https://github.com/relekang/python-semantic-release</repository>
      <description>Automated Semantic Versioning for Python</description>
      <sources>projects/python-semantic-release</sources>
      <modules>
        <module>semantic_release.dist</module>
      </modules>
    </project>
    <project>
      <name>flutes</name>
      <version>0.3.0</version>
      <repository>https://github.com/huzecong/flutes</repository>
      <description>Utilities for Python</description>
      <sources>projects/flutes</sources>
      <modules>
        <module>flutes.math</module>
      </modules>
    </project>
    <project>
      <name>pyMonet</name>
      <version>0.12.0</version>
      <repository>https://github.com/przemyslawjanpietrzak/pyMonet</repository>
      <description>High abstract library for functional programming</description>
      <sources>projects/pyMonet</sources>
      <modules>
        <module>pymonet.semigroups</module>
      </modules>
    </project>
    <project>
      <name>dataclasses-json</name>
      <version>0.5.2</version>
      <repository>https://github.com/lidatong/dataclasses-json</repository>
      <description>Encoding and Decoding Dataclasses to and from JSON</description>
      <sources>projects/dataclasses-json</sources>
      <modules>
        <module>dataclasses_json.undefined</module>
      </modules>
    </project>
  </projects>
</experiment>
